---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bob-admin
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: claster-admin
  apiGroup: rbac.authorization.k8s.io