apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentreplica
  labels:
    app: paymentreplica
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: paymentreplica
      app: paymentreplica
  template:
    metadata:
      labels:
        tier: paymentreplica
        app: paymentreplica
    spec:
      containers:
      - name: paymentreplica
        image: bartolamey/mcfrontend:0.0.1
        env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
