apiVersion: v1
kind: Pod
metadata:
  name: web-app-for-k8s
  labels:
    key: "value"

spec:

  initContainers:
  - name: init-busybox
    image: busybox
    volumeMounts:
    - name: app
      mountPath: /app
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']

  containers:
  - name: ngnix
    image: bartolamey/web_app_for_k8s:0.11
    volumeMounts:
    - name: app
      mountPath: /app

  volumes:
    - name: app
      emptyDir: {}